export const NAME_ERROR = {
  please_enter_your_current_password: 'Vui lòng nhập vào mật khẩu hiện tại.',
  please_enter_a_new_password: 'Vui lòng nhập vào mật khẩu mới.',
  please_enter_token: 'Vui lòng nhập token.',
  authentication_token_not_found_or_invalid: 'Token xác thực không tìm thấy hoặc không hợp lệ.',
  email_or_phone_number_registered_with_another_account: 'Email hoặc số điện thoại đã được đăng ký với một tài khoản khác.',
  username_available: 'Tên đăng nhập đã tồn tại',
  coupon_code_does_not_exist_or_has_expired: 'Mã giảm giá không tồn tại hoặc đã hết hiệu lực.',
  please_enter_your_username: 'Vui lòng nhập vào tên đăng nhập.',
  please_enter_the_recipients_name: 'Vui lòng nhập tên người nhận.',
  please_enter_the_recipients_phone_number: 'Vui lòng nhập số điện thoại người nhận.',
  please_enter_your_address: 'Vui lòng nhập địa chỉ.',
  please_select_ward: 'Vui lòng chọn phường.',
  please_select_a_county: 'Vui lòng chọn quận.',
  please_select_a_city: 'Vui lòng chọn thành phố.',
  please_enter_your_phone_number: 'Vui lòng nhập vào số điện thoại.',
  please_enter_password: 'Vui lòng nhập vào mật khẩu.',
  the_phone_number_is_already_registered_with_another_account: 'Số điện thoại đã được đăng ký với một tài khoản khác',
  no_referral_code_exists: 'Không tồn tại mã giới thiệu',
  Cant_be_left_blank: 'Không được để trống',
  device_already_exists: 'Đã tồn tại thiết bị',
  title_is_required: 'Title is required.',
  content_is_required: 'Content is required.',
  first_name_and_last_name_are_required: 'First name and last name are required.',
  please_enter_your_full_name: 'Vui lòng nhập vào tên đầy đủ.',
  please_enter_your_full_phone_number: 'Vui lòng nhập vào số điện thoại đầy đủ.',
  phone_number_registered_with_another_account: 'Số điện thoại đã được đăng ký với một tài khoản khác.',
  cannot_update_this_bill_item: 'Cannot update this bill item',
  orders_with_unfinished_receipts: 'Đơn hàng có phiếu thu chưa hoàn thành',
  cannot_delete_this_bill: 'Cannot delete this bill',
  cannot_cancel_this_bill: 'Cannot cancel this bill',
  this_bill_item_is_not_completed: 'This bill item is not completed',
  this_bill_is_not_completed: 'This bill is not completed',
  this_appointment_is_not_completed: 'This appointment is not completed',
  
}
