export const PERMISSION_CORE_ACTIONS = {
  read: 'Đọc',
  write: 'Thêm mới',
  delete: 'Xóa',
  update: 'Chỉnh sửa',
  download:'Tải về',
  admin: 'Quản trị'
}

export const RESOURCES_NAME = {
  notificationBotManager: '[HT] Quản lý thông báo tự động',
  branch: '[HT] Quản lý chi nhánh',
  userGroup: '[HT] Quản lý nhóm người dùng',
  user: '[HT] Quản lý người dùng',
  employee: '[HT] Danh sách nhân viên',
  giveCoupon: '[HT] Quản lý chương trình khuyến mại',
  customer: '[HT] Quản lý khách hàng',
  potentialCustomer: '[WH] Import khách hàng tiềm năng',
  patient: '[HT] Quản lý bệnh nhân',
  cms: '[HT] Quản lý CMS',
  userGroupService: '[HT] Quản lý nhóm dịch vụ',
  referral: '[WH] Giới thiệu',
  chartClinic: '[PK] Quản lý biểu đồ phòng khám',
  partner: '[PK] Quản lý phòng khám',
  appointment: '[PK] Quản lý đặt lịch',
  affiliatedAppointment: '[PK] Quản lý lịch hẹn liên kết',
  order: '[NT] Quản lý đơn hàng',
  pharmacy: '[NT] Quản lý nhà thuốc',
  whBill: '[WH] Quản lý đơn hàng',
  whAppointment: '[WH] Quản lý lịch hẹn',
  whUpdateBillStatus: '[WH] Cập nhật trạng thái đơn hàng',
  whUpdateReceiptAndPaymentVoucherStatus: '[WH] Cập nhật trạng thái phiếu thu chi',
  whHistoryLog: '[WH] Xem lịch sử đơn hàng',
  whPartner: '[WH] Quản lý đối tác',
  whSetting: '[WH] Quản lý cài đặt',
  quotations: '[WH] Quản lý đơn hàng tạm',
  whPackageLevel: '[WH] Quản lý gói dịch vụ',
  banner: '[WH] Quản lý banner',
  potentialPartner: '[WH] Import đối tác',
  whCourseTraining: '[WH] Quản lý khoá đào tạo',
  whRevenuePartner: '[WH] Quản lý doanh thu đối tác',
  whRevenueCustomer: '[WH] Quản lý doanh thu khách hàng',
  whRevenueSystem: '[WH] Quản lý doanh thu hệ thống',
  whVouchers: '[WH] Quản lý sổ quỹ',
  whbeginninFund: '[WH] Quản lý quỹ đầu kì',
  whTransaction: '[WH] Quản lý giao dịch',
  whMedicalEquipment: '[WH] Quản lý thiết bị y tế',
  whTips: '[WH] Quản lý thưởng phạt',
  whHealthcareFacility: '[WH] Nơi thực hiện dịch vụ',
  whRequestVoucher: '[WH] Yêu cầu rút tiền',
  whappointmentCancelPartner: '[WH] Yêu cầu huỷ cuộc hẹn',
  whChartDashboardHealthCare: '[WH] Quản lý biểu đồ World Health',
  warehouse: '[WH] Quản lý kho',
  keywordSearch: '[WH] Quản lý từ khóa',
  whServiceGroup: '[WH] Nhóm dịch vụ',
  whService: '[WH] Dịch vụ',
  whTimeRegulation: '[WH] Quy định thời gian',
  whCredential: '[WH] Bằng cấp',
  whPosition: '[WH] Chức vụ',
  whExperience: '[WH] Kinh nghiệm',
  whProfessionalStaff: '[WH] Cán bộ chuyên môn',
  whJobStandard: '[WH] Định mức công việc',
  whCustomerEvaluation: '[WH] Khách hàng đánh giá',
  whServiceBookingInstructionsSetup: '[WH] Setup hướng dẫn đặt dịch vụ',
  medicalClinic: '[HT] Danh sách các bác sĩ liên kết với WorldCareVN',
  announcement: '[HT] Tin tức',
  configuration: '[HT] Thiết lập',
  leadingPartner: '[HT] Đối tác hàng đầu',
  discountCode: '[HT] Mã giảm giá',
  policy: '[HT] Chính sách',
  shippingCompany: '[HT] Nhà vận chuyển',
  highlight: '[HT] Highlight',
  whErrorOfPharmacy: '[WH] Hệ thống báo lỗi ở kho',
  productDelivery: '[WH] Quản lý chuyển kho',
  whServiceBranch:'[HT] Đăng ký hoạt động dịch vụ',
  acceptService:'[HT] Phê duyệt đăng ký hoạt động dịch vụ',
  todoConfigStatus: '[HT] Quản lý cấu hình trạng thái công việc',
  todoList: '[HT] Quản lý công việc',
  system:'[HT] Quản lý phiên bản (App)',
  whHistoryLogVoucher: '[WH] Xem lịch sử phiếu',
  history:'[WH] Lịch sử dịch vụ',
}